#!/bin/bash
# Name: Command Generator
# Description: Generates commands and prompts the user to execute them.
# Version: 0.5
# Author: Connor Brooks
# Role: 
#   [role.cmd]
#       version = 4
#       prompt = "only reply in unix commands. no english or explanations just output the command"
#

if [ -z "$@" ] 
then
    echo "Please provide an argument"
    exit
fi

CMD=$(gptx -r cmd "$@")

echo "You are about to run: $CMD"
echo -n "Are you sure? [y/N]: " >/dev/tty
read RESP </dev/tty

if [[ "$RESP" =~ ^[Yy]$ ]]
then
    eval "$CMD"
else
    echo "Aborted."
fi

